name: Build variant

on:
  workflow_call:
    inputs:
      CMAKE_PROJECT_DIR:
        type: string
        required: true
      CMAKE_PRESET:
        type: string
        required: true
      BINARY_DIR:
        type: string
        required: true
      BINARY_NAME:
        type: string
        required: true
      BINARY_NAME_VAR:
        type: string
        required: true
      BINARY_VERSION:
        type: string
        required: true
      BINARY_VERSION_VAR:
        type: string
        required: true
      
      VARIANT:
        type: string
        required: true
    outputs:
      ARTIFACT_NAME:
        value: ${{ jobs.build.outputs.ARTIFACT_NAME }}
      PRODUCT_NAME:
        value: ${{ jobs.build.outputs.PRODUCT_NAME }}
      PRODUCT_VERSION:
        value: ${{ jobs.build.outputs.PRODUCT_VERSION }}
      BINARY_NAME:
        value: ${{ jobs.build.outputs.BINARY_NAME }}

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    outputs:
      ARTIFACT_NAME: ${{ steps.export.outputs.ARTIFACT_NAME }}
      BINARY_NAME: ${{ steps.export.outputs.BINARY_NAME }}
      PRODUCT_NAME: ${{ steps.export.outputs.PRODUCT_NAME }}
      PRODUCT_VERSION: ${{ steps.export.outputs.PRODUCT_VERSION }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive 
    
    - name: Configure CMake
      run: cmake --preset ${{inputs.CMAKE_PRESET}}

    - name: Build
      run: cmake --build ${{inputs.BINARY_DIR}} --config ${{env.BUILD_TYPE}}
    
    - id: export
      shell: pwsh
      run: |
        $PRODUCT_NAME = If (![string]::IsNullOrEmpty("${{inputs.BINARY_NAME}}")) {"${{inputs.BINARY_NAME}}"} Else { cmake -L -N ${{inputs.BINARY_DIR}} | grep "${{inputs.BINARY_NAME_VAR}}" | %{$_ -replace "${{inputs.BINARY_NAME_VAR}}:STRING=",""} }
        $PRODUCT_VERSION = If (![string]::IsNullOrEmpty("${{inputs.BINARY_VERSION}}")) {"${{inputs.BINARY_VERSION}}"} Else { cmake -L -N ${{inputs.BINARY_DIR}} | grep "^${{inputs.BINARY_VERSION_VAR}}" | %{$_ -replace "${{inputs.BINARY_VERSION_VAR}}:STRING=",""} }
        $BINARY_NAME = "${PRODUCT_NAME}.dll"
        $BINARY_PATH = "${{inputs.BINARY_DIR}}/${{inputs.CMAKE_PROJECT_DIR}}/${{env.BUILD_TYPE}}/${BINARY_NAME}"
        $MARKETING_SUFFIX = "${{inputs.VARIANT}}".ToUpper()
        $ARTIFACT_NAME = "${{inputs.PRODUCT_NAME}} $MARKETING_SUFFIX"

        echo "::set-output name=PRODUCT_NAME::$PRODUCT_NAME"
        echo "::set-output name=PRODUCT_VERSION::$PRODUCT_VERSION"
        echo "::set-output name=ARTIFACT_NAME::$ARTIFACT_NAME"
        echo "::set-output name=BINARY_PATH::$BINARY_PATH"
        echo "::set-output name=BINARY_NAME::$BINARY_NAME"
        echo "Built $BINARY_NAME ✅"
        echo "Location: $BINARY_PATH"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ steps.export.outputs.ARTIFACT_NAME }}
        if-no-files-found: error
        path: ${{ steps.export.outputs.BINARY_PATH }}
      
